AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Zapier Triggers API - Phase 1 MVP Core Event Ingestion

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        EVENTS_TABLE_NAME: !Ref EventsTable
        API_KEYS_TABLE_NAME: !Ref APIKeysTable
        AWS_XRAY_TRACING_NAME: triggers-api

Resources:
  TriggersApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      Auth:
        Authorizers:
          ApiKeyAuthorizer:
            AuthorizerPayloadFormatVersion: '2.0'
            FunctionArn: !GetAtt ApiKeyAuthorizer.Arn
            FunctionInvokeRole: !GetAtt ApiKeyAuthorizerInvokeRole.Arn
            Identity:
              Headers:
                - authorization
              ReauthorizeEvery: 300  # 5 minutes cache
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
        AllowHeaders:
          - "*"

  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.handler
      Description: Events API handler for ingestion and retrieval
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref APIKeysTable
      Events:
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /health
            Method: GET
        CreateEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /events
            Method: POST
            # Auth disabled - /events endpoint is publicly accessible
        GetEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /events/{id}
            Method: GET
        ListEvents:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /events
            Method: GET
        GetInbox:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /inbox
            Method: GET
        AcknowledgeEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref TriggersApi
            Path: /events/{id}/acknowledge
            Method: POST

  # Authorizer IAM Role
  ApiKeyAuthorizerInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Policies:
        - PolicyName: DynamoDBReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource: !GetAtt APIKeysTable.Arn

  # API Key Authorizer Lambda Function
  ApiKeyAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: auth.authorizer.lambda_handler
      Description: API key authentication authorizer
      Runtime: python3.11
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          API_KEYS_TABLE_NAME: !Ref APIKeysTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref APIKeysTable

  # DynamoDB Tables
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-events'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: dev
        - Key: Service
          Value: triggers-api

  APIKeysTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-api-keys'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: key_id
          AttributeType: S
      KeySchema:
        - AttributeName: key_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: dev
        - Key: Service
          Value: triggers-api

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com'
  HealthEndpoint:
    Description: Health check endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com/health'
  EventsEndpoint:
    Description: Events API endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com/events'
  EventsFunctionArn:
    Description: Events Function ARN
    Value: !GetAtt EventsFunction.Arn
  ApiKeyAuthorizerArn:
    Description: API Key Authorizer Function ARN
    Value: !GetAtt ApiKeyAuthorizer.Arn
  EventsTableName:
    Description: Events DynamoDB table name
    Value: !Ref EventsTable
  APIKeysTableName:
    Description: API Keys DynamoDB table name
    Value: !Ref APIKeysTable

  # CloudWatch Dashboard for monitoring
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${AWS::StackName}-monitoring'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["TriggersAPI", "EventCreated", {"stat": "Sum"}],
                  [".", "EventDelivered", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Event Throughput",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["TriggersAPI", "InboxDepth", {"stat": "Maximum"}]
                ],
                "period": 300,
                "stat": "Maximum",
                "region": "${AWS::Region}",
                "title": "Inbox Depth",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Duration", {"stat": "Average"}],
                  [".", ".", {"stat": "p95"}],
                  [".", ".", {"stat": "p99"}]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "API Latency (Lambda Duration)"
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Errors", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Lambda Errors",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "Lambda Invocations",
                "yAxis": {"left": {"min": 0}}
              }
            },
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ApiGateway", "Count", {"stat": "Sum"}],
                  [".", "4XXError", {"stat": "Sum"}],
                  [".", "5XXError", {"stat": "Sum"}]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}",
                "title": "API Gateway Metrics",
                "yAxis": {"left": {"min": 0}}
              }
            }
          ]
        }

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com'
  HealthEndpoint:
    Description: Health check endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com/health'
  EventsEndpoint:
    Description: Events API endpoint URL
    Value: !Sub 'https://${TriggersApi}.execute-api.${AWS::Region}.amazonaws.com/events'
  EventsFunctionArn:
    Description: Events Function ARN
    Value: !GetAtt EventsFunction.Arn
  ApiKeyAuthorizerArn:
    Description: API Key Authorizer Function ARN
    Value: !GetAtt ApiKeyAuthorizer.Arn
  EventsTableName:
    Description: Events DynamoDB table name
    Value: !Ref EventsTable
  APIKeysTableName:
    Description: API Keys DynamoDB table name
    Value: !Ref APIKeysTable
